//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int ID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
